project:
  type: website
  output-dir: docs          # publish folder for GitHub Pages

website:
  title: "Raameen Ahmed"

  navbar:
    left:
      - text: "Projects"
        file: projects.qmd   # use file: for internal pages
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/raameena
      - icon: envelope
        href: mailto:raameenahmed1@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/raameena/

format:
  html:
    theme:                   # <─ only two lines needed for dark-mode
      light: cosmo
      dark:  darkly
    css: styles.css
